apiVersion: xgeeks.ki.com/v1beta1
kind: Dummy
metadata:
  name: mycrd
spec:
  replicas: 3
  quote: You know you're in love when you can't fall asleep because reality is finally better than your dreams.
  sleep: 30
  extra:
  - Dr. Seuss
