apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myoperator
  name: myoperator
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myoperator
  type: NodePort
status:
  loadBalancer: {}
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myoperator
  name: myoperator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myoperator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myoperator
    spec:
      serviceAccount: myoperator
      containers:
      - env:
        - name: SERVER_PORT
          value: "80"
        - name: SHOW_HEALTH_COMPONENTS
          value: "never"
        image: operator:0.0.1-SNAPSHOT
        name: myoperator
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /dummy/health
            port: 80
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /dummy/info
            port: 80
        resources: {}
status: {}
