apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: myoperator
rules:
  - apiGroups:
    - xgeeks.ki.com
    resources: ["dummies", "dummies/status"]
    verbs:
    - '*'
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs: ["get", "list"]
  - apiGroups: 
    - apps
    resources:
    - deployments
    verbs: ["get", "list", "create", "patch", "watch"]
  - apiGroups: ["", "events.k8s.io"]
    resources:
    - events
    verbs:
    - create
---
---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: myoperator
---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: myoperator-admin
subjects:
  - kind: ServiceAccount
    name: myoperator
    namespace: default
roleRef:
  kind: ClusterRole
  name: myoperator
  apiGroup: ""
